<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AngelOne.SmartApi.Clients" Version="2.0.0" />
    <PackageReference Include="Google.Apis" Version="1.72.0" />
    <PackageReference Include="Google.Apis.Sheets.v4" Version="1.70.0.3819" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="Otp.NET" Version="1.4.0" />
    <PackageReference Include="RestSharp" Version="112.1.0" />
    <PackageReference Include="System.Security.Permissions" Version="9.0.9" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="AngelBroking">
      <HintPath>..\..\..\Downloads\smartapi-dotnet-main\smartapi-dotnet-main\DLL\AngelBroking.dll</HintPath>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>..\..\..\Downloads\smartapi-dotnet-main\smartapi-dotnet-main\DLL\Newtonsoft.Json.dll</HintPath>
    </Reference>
    <Reference Include="System.Reactive">
      <HintPath>..\..\..\Downloads\smartapi-dotnet-main\smartapi-dotnet-main\DLL\System.Reactive.dll</HintPath>
    </Reference>
    <Reference Include="System.Reactive.Linq">
      <HintPath>..\..\..\Downloads\smartapi-dotnet-main\smartapi-dotnet-main\DLL\System.Reactive.Linq.dll</HintPath>
    </Reference>
    <Reference Include="Websocket.Client">
      <HintPath>..\..\..\Downloads\smartapi-dotnet-main\smartapi-dotnet-main\DLL\Websocket.Client.dll</HintPath>
    </Reference>
    <Reference Include="zlib.net">
      <HintPath>..\..\..\Downloads\smartapi-dotnet-main\smartapi-dotnet-main\DLL\zlib.net.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <None Update="Data\AccesTokenData.Json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Data\Angel_Master_OCT.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Data\credentials.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Data\Settings.Json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
